version: '3.8'
services:

  ui:
    container_name: ui
    restart: always
    build: './ui'
    ports:
      - "80:3000"

  api1:
    container_name: api1
    build: './api/API1'
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "./api/API1:/api"
